### ISSUE TITLE
Retail version does not match the doc

### ISSUE THREAD

**Issue by vitor-l** [googleapis/elixir-google-api#10762]
#### Environment details

  - Programming language: Elixir
  - OS: Linux
  - Language runtime version: Elixir 1.14.4 (compiled with Erlang/OTP 25)
  - Package version: (that is the problem)

#### Steps to reproduce

  1. Try to install ```:google_api_retail``` in 0.8 version

Hello! I'm trying to install the recommended version of the ```:google_api_retail``` (https://github.com/googleapis/elixir-google-api/blob/main/clients/retail/README.md#googleapiretail), but it can't be installed.

```elixir
> mix deps.get

Resolving Hex dependencies...
Resolution completed in 0.057s
Because your app depends on google_api_retail ~> 0.8 which doesn't match any versions, version solving failed.
** (Mix) Hex dependency resolution failed
```

So, I checked the Hex doc and the latest available version is 0.7.0 (https://hexdocs.pm/google_api_retail/api-reference.html).

The problem is: I need the latest version to use some functions, like _retail_projects_locations_catalogs_branches_products_add_local_inventories_

Can someone help me?

**Comment by felipe-rodrigues1** [comment]
I have the same issue. I tried to install recommended version of google_api_retail but was not able to. Any solutions?

**Comment by alves-raphael** [comment]
Same problem here.

**Comment by KaduMoura** [comment]
same here...

folks, can u help us?

@dazuma @chingor13 @stefanluptak @bshaffer @JustinBeckwith @jaegerpicker @milmazz 

thanks in advance!

**Comment by stefanluptak** [comment]
When I do `mix hex.info google_api_retail` I get this response:

```
# mix hex.info google_api_retail                                                                                                                               ─╯
Retail API client library. Cloud Retail service enables customers to build end-to-end personalized recommendation systems without requiring a high level of expertise in machine learning, recommendation system, or Google Cloud.

Config: {:google_api_retail, "~> 0.7.0"}
Releases: 0.7.0, 0.6.1, 0.6.0, 0.5.0, 0.4.0, 0.3.1, 0.3.0, 0.2.1

Licenses: Apache 2.0
Links:
  GitHub: https://github.com/googleapis/elixir-google-api/tree/master/clients/retail
  Homepage: https://cloud.google.com/recommendations
```

Apparently, the `0.8.0` version was not released yet, but you can use the GitHub directly by putting this
`{:google_api_retail, github: "googleapis/elixir-google-api", sparse: "clients/retail"}` into your `mix.exs` file `deps` section.
